Local/src/Entity/Cursada.php
<?php

namespace App\Entity;

use App\Repository\CursadaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CursadaRepository::class)]
class Cursada
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $ciclo_lectivo = null;

    #[ORM\ManyToOne(inversedBy: 'cursada')]
    private ?Alumno $alumno = null;

    #[ORM\OneToMany(mappedBy: 'cursada', targetEntity: CursadaDocente::class)]
    private Collection $cursada_docente;

    #[ORM\ManyToOne(inversedBy: 'cursada')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Comision $comision = null;

    #Error al agregar otro alumno con una asignatura ya existente


    #[ORM\OneToMany(mappedBy: 'cursada', targetEntity: ExamenAlumno::class, orphanRemoval: true)]
    private Collection $examenAlumnos;

    #[ORM\Column]
    private ?bool $libre = null;

    #[ORM\Column(nullable: true)]
    private ?int $nota1 = null;

    #[ORM\Column(nullable: true)]
    private ?int $nota2 = null;

    #[ORM\ManyToOne(inversedBy: 'cursada')]
    private ?Asignatura $asignatura = null;

    public function __construct()
    {
        $this->cursada_docente = new ArrayCollection();
        $this->examenAlumnos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCicloLectivo(): ?int
    {
        return $this->ciclo_lectivo;
    }

    public function setCicloLectivo(int $ciclo_lectivo): static
    {
        $this->ciclo_lectivo = $ciclo_lectivo;

        return $this;
    }

    public function getAlumno(): ?Alumno
    {
        return $this->alumno;
    }

    public function setAlumno(?Alumno $alumno): static
    {
        $this->alumno = $alumno;

        return $this;
    }

    /**
     * @return Collection<int, CursadaDocente>
     */
    public function getCursadaDocente(): Collection
    {
        return $this->cursada_docente;
    }

    public function addCursadaDocente(CursadaDocente $cursadaDocente): static
    {
        if (!$this->cursada_docente->contains($cursadaDocente)) {
            $this->cursada_docente->add($cursadaDocente);
            $cursadaDocente->setCursada($this);
        }

        return $this;
    }

    public function removeCursadaDocente(CursadaDocente $cursadaDocente): static
    {
        if ($this->cursada_docente->removeElement($cursadaDocente)) {
            // set the owning side to null (unless already changed)
            if ($cursadaDocente->getCursada() === $this) {
                $cursadaDocente->setCursada(null);
            }
        }

        return $this;
    }

    public function getComision(): ?Comision
    {
        return $this->comision;
    }

    public function setComision(?Comision $comision): static
    {
        $this->comision = $comision;

        return $this;
    }


    /**
     * @return Collection<int, ExamenAlumno>
     */
    public function getExamenAlumnos(): Collection
    {
        return $this->examenAlumnos;
    }

    public function addExamenAlumno(ExamenAlumno $examenAlumno): static
    {
        if (!$this->examenAlumnos->contains($examenAlumno)) {
            $this->examenAlumnos->add($examenAlumno);
            $examenAlumno->setCursada($this);
        }

        return $this;
    }

    public function removeExamenAlumno(ExamenAlumno $examenAlumno): static
    {
        if ($this->examenAlumnos->removeElement($examenAlumno)) {
            // set the owning side to null (unless already changed)
            if ($examenAlumno->getCursada() === $this) {
                $examenAlumno->setCursada(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return 'Alumno: '.$this->getAlumno()->getPersona()->getNombre().'. Asignatura: '.$this->getAsignatura()->getNombre(); //capas que hay que cambiar esto
    }

    public function isLibre(): ?bool
    {
        return $this->libre;
    }

    public function setLibre(bool $libre): static
    {
        $this->libre = $libre;

        return $this;
    }

    public function getNota1(): ?int
    {
        return $this->nota1;
    }

    public function setNota1(?int $nota1): static
    {
        $this->nota1 = $nota1;

        return $this;
    }

    public function getNota2(): ?int
    {
        return $this->nota2;
    }

    public function setNota2(?int $nota2): static
    {
        $this->nota2 = $nota2;

        return $this;
    }

    public function getAsignatura(): ?Asignatura
    {
        return $this->asignatura;
    }

    public function setAsignatura(?Asignatura $asignatura): static
    {
        $this->asignatura = $asignatura;

        return $this;
    }
}

Local/src/Form/CursadaType.php
<?php

namespace App\Form;

use App\Entity\Cursada;
use App\Entity\Alumno;
use App\Entity\Comision;
use App\Entity\Asignatura;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\Range;


class CursadaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ciclo_lectivo',NumberType::class,[
                'label' => 'Ciclo Lectivo',
                'attr' => ['class' => 'form-control']
            ])
            ->add('alumno',EntityType::class,[
                'class' => Alumno::class,
                'choice_label' => 'persona.nombre',
                'attr' => ['class' => 'form-control']
            ])
            ->add('comision',EntityType::class,[
                'class' => Comision::class,
                'choice_label' => 'comision',
                'attr' => ['class' => 'form-control']
            ])
            ->add('asignatura',EntityType::class,[
                'class' => Asignatura::class,
                'choice_label' => 'nombre',
                'attr' => ['class' => 'form-control']
            ])
            ->add('libre', null, [
                'label' => 'Libre',
                'attr' => ['class' => 'form-control']
            ])
            ->add('nota1', NumberType::class, [
                'label' => 'Primera Nota',
                'attr' => ['class' => 'form-control'],
                'constraints' => [
                    new Range([
                        'min' => 1,
                        'max' => 10,
                        'minMessage' => 'Rango de notas entre 1 y 10',
                        'maxMessage' => 'Rango de notas entre 1 y 10'
                    ])
                ]
            ])
            ->add('nota2', NumberType::class, [
                'label' => 'Segunda Nota',
                'attr' => ['class' => 'form-control'],
                'constraints' => [
                    new Range([
                        'min' => 1,
                        'max' => 10,
                        'minMessage' => 'Rango de notas entre 1 y 10',
                        'maxMessage' => 'Rango de notas entre 1 y 10'
                    ])
                ]
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cursada::class,
        ]);
    }
}

Local/src/Controller/CursadaController.php
<?php

namespace App\Controller;

use App\Entity\Cursada;
use App\Form\CursadaType;
use App\Repository\CursadaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/cursada')]
class CursadaController extends AbstractController
{
    #[Route('/', name: 'app_cursada_index', methods: ['GET'])]
    public function index(CursadaRepository $cursadaRepository): Response
    {
        return $this->render('cursada/index.html.twig', [
            'cursadas' => $cursadaRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_cursada_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CursadaRepository $cursadaRepository): Response
    {
        $cursada = new Cursada();
        $form = $this->createForm(CursadaType::class, $cursada);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cursadaRepository->save($cursada, true);

            return $this->redirectToRoute('app_cursada_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cursada/new.html.twig', [
            'cursada' => $cursada,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cursada_show', methods: ['GET'])]
    public function show(Cursada $cursada): Response
    {
        return $this->render('cursada/show.html.twig', [
            'cursada' => $cursada,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_cursada_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cursada $cursada, CursadaRepository $cursadaRepository): Response
    {
        $form = $this->createForm(CursadaType::class, $cursada);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cursadaRepository->save($cursada, true);

            return $this->redirectToRoute('app_cursada_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cursada/edit.html.twig', [
            'cursada' => $cursada,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cursada_delete', methods: ['POST'])]
    public function delete(Request $request, Cursada $cursada, CursadaRepository $cursadaRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cursada->getId(), $request->request->get('_token'))) {
            $cursadaRepository->remove($cursada, true);
        }

        return $this->redirectToRoute('app_cursada_index', [], Response::HTTP_SEE_OTHER);
    }
}

Local/templates/cursada/_delete_form.html.twig
<form method="post" action="{{ path('app_cursada_delete', {'id': cursada.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cursada.id) }}">
    <button class="btn">Borrar</button>
</form>

Local/templates/cursada/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Cursada{% endblock %}

{% block body %}
    <h1>Editar Cursada</h1>

    {{ include('cursada/_form.html.twig', {'button_label': 'Actualizar'}) }}

    <a href="{{ path('app_cursada_index') }}">Volver</a>

    {{ include('cursada/_delete_form.html.twig') }}
{% endblock %}

Local/templates/cursada/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cursadas{% endblock %}

{% block body %}
    <h1>Cursadas de Estudiantes</h1>

    <table class="table">
        <thead>
            <tr>
                
                <th>Ciclo_lectivo</th>
                <th>Apellido</th>
                <th>Nombre</th>
                <th>Tecnicatura</th>
                <th>Asignatura</th>
                <th>Comision</th>
                <th>Libre</th>
                <th>Nota1</th>
                <th>Nota2</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for cursada in cursadas %}
            <tr>
                
                <td>{{ cursada.cicloLectivo }}</td>
                <td>{{ cursada.Alumno.Persona.Apellido }}</td>
                <td>{{ cursada.Alumno.Persona.nombre }}</td>
                <td>{{ cursada.Asignatura.Tecnicatura }}</td>
                <td>{{ cursada.Asignatura }}</td>
                <td>{{ cursada.Comision }}</td>
                <td>{{ cursada.Libre }}</td>
                <td>{{ cursada.Nota1 }}</td>
                <td>{{ cursada.Nota2 }}</td>
                <td>
                    <a href="{{ path('app_cursada_show', {'id': cursada.id}) }}">Mostrar</a>
                    {% if is_granted ('ROLE_SUPER_ADMIN') or is_granted ('ROLE_ADMIN') %}

                    <a href="{{ path('app_cursada_edit', {'id': cursada.id}) }}">Editar</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no se encontraron registros</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% if is_granted ('ROLE_SUPER_ADMIN') or is_granted ('ROLE_ADMIN') %}

    <a href="{{ path('app_cursada_new') }}">Crear cursada</a>
    {% endif %}
{% endblock %}

Local/templates/cursada/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nueva Cursada{% endblock %}

{% block body %}
<div class="container">

    <h1>Crear Cursada</h1>

    {{ include('cursada/_form.html.twig') }}

    <a href="{{ path('app_cursada_index') }}">Volver</a>
</div>
{% endblock %}

Local/templates/cursada/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cursada{% endblock %}

{% block body %}
    <h1>Cursada</h1>

    <table class="table">
        <tbody>
           
            <tr>
                <th>Ciclo_lectivo</th>
                <td>{{ cursada.cicloLectivo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_cursada_index') }}">Volver</a>

    <a href="{{ path('app_cursada_edit', {'id': cursada.id}) }}">Editar</a>

    {{ include('cursada/_delete_form.html.twig') }}
{% endblock %}