Local/src/Entity/Alumno.php
<?php

namespace App\Entity;

use App\Repository\AlumnoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AlumnoRepository::class)]
class Alumno
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $titulo_sec = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $escuela_sec = null;

    #[ORM\Column(nullable: true)]
    private ?int $anio_egreso = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Persona $persona = null;

    #[ORM\OneToMany(mappedBy: 'alumno', targetEntity: Cursada::class)]
    private Collection $cursada;


    public function __construct()
    {
        $this->cursada = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTituloSec(): ?string
    {
        return $this->titulo_sec;
    }

    public function setTituloSec(?string $titulo_sec): static
    {
        $this->titulo_sec = $titulo_sec;

        return $this;
    }

    public function getEscuelaSec(): ?string
    {
        return $this->escuela_sec;
    }

    public function setEscuelaSec(?string $escuela_sec): static
    {
        $this->escuela_sec = $escuela_sec;

        return $this;
    }

    public function getAnioEgreso(): ?int
    {
        return $this->anio_egreso;
    }

    public function setAnioEgreso(?int $anio_egreso): static
    {
        $this->anio_egreso = $anio_egreso;

        return $this;
    }

    public function getPersona(): ?Persona
    {
        return $this->persona;
    }

    public function setPersona(Persona $persona): static
    {
        $this->persona = $persona;

        return $this;
    }

    /**
     * @return Collection<int, Cursada>
     */
    public function getCursada(): Collection
    {
        return $this->cursada;
    }

    public function addCursada(Cursada $cursada): static
    {
        if (!$this->cursada->contains($cursada)) {
            $this->cursada->add($cursada);
            $cursada->setAlumno($this);
        }

        return $this;
    }

    public function removeCursada(Cursada $cursada): static
    {
        if ($this->cursada->removeElement($cursada)) {
            // set the owning side to null (unless already changed)
            if ($cursada->getAlumno() === $this) {
                $cursada->setAlumno(null);
            }
        }

        return $this;
    }


    public function __toString(): string
    {
        return $this->getPersona()->getNombre();
    }
}

Local/src/Form/AlumnoType.php
<?php

namespace App\Form;

use App\Entity\Alumno;
use App\Form\PersonaType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

class AlumnoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titulo_sec',TextType::class,[
                'label' => 'Titulo Secundario',
                'attr' => ['class' => 'form-control']
            ])
            ->add('escuela_sec',TextType::class,[
                'label' => 'Escuela Secundaria',
                'attr' => ['class' => 'form-control']
            ])
            ->add('anio_egreso',NumberType::class,[
                'label' => 'Año de Egreso',
                'attr' => ['class' => 'form-control']
            ])
            ->add('persona',EntityType::class,[
                'class' => Persona::class,
                'query_builder' => function(EntityRepository $er) : QueryBuilder {
                    return $er->createQueryBuilder('p')
                    ->leftJoin('App\Entity\Alumno','a','WITH','p.id = a.persona')
                    ->leftJoin('App\Entity\Docente','d','WITH','p.id = d.persona')
                    ->where('a.persona IS NULL')
                    ->andWhere('d.persona IS NULL');
                },
                'choice_label' => function($persona){
                    return 'Nombre : ' . $persona->getNombre() . ' , '. 'Apellido :' . $persona->getApellido() . ' , ' . 'Dni :' . $persona->getDnipasaporte();
                },
                'attr' => ['class' => 'form-control']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Alumno::class,
        ]);
    }
}

Local/src/Controller/AlumnoController.php
<?php

namespace App\Controller;

use App\Entity\Alumno;
use App\Entity\Persona;
use App\Form\AlumnoType;
use App\Repository\AlumnoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/alumno')]
class AlumnoController extends AbstractController
{
    #[Route('/', name: 'app_alumno_index', methods: ['GET'])]
    public function index(AlumnoRepository $alumnoRepository): Response
    {
        return $this->render('alumno/index.html.twig', [
            'alumnos' => $alumnoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_alumno_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AlumnoRepository $alumnoRepository): Response
    {
        $alumno = new Alumno();
        $form = $this->createForm(AlumnoType::class, $alumno);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $alumnoRepository->save($alumno, true);

            return $this->redirectToRoute('app_alumno_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('alumno/new.html.twig', [
            'alumno' => $alumno,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_alumno_show', methods: ['GET'])]
    public function show(Alumno $alumno): Response
    {
        return $this->render('alumno/show.html.twig', [
            'alumno' => $alumno,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_alumno_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Alumno $alumno, AlumnoRepository $alumnoRepository): Response
    {
        $form = $this->createForm(AlumnoType::class, $alumno);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $alumnoRepository->save($alumno, true);

            return $this->redirectToRoute('app_alumno_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('alumno/edit.html.twig', [
            'alumno' => $alumno,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_alumno_delete', methods: ['POST'])]
    public function delete(Request $request, Alumno $alumno, AlumnoRepository $alumnoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$alumno->getId(), $request->request->get('_token'))) {
            $alumnoRepository->remove($alumno, true);
        }

        return $this->redirectToRoute('app_alumno_index', [], Response::HTTP_SEE_OTHER);
    }

    public function search_alumnos(Request $request,AlumnoRepository $alumnoRepository):Response{
        $dni = $request->query->get('dni');        
        $persona = $this->getDoctrine()->getRepository(Persona::class)->findBy(['dni_pasaporte' => $dni]);
        $persona_id = array_values($persona);
        $value = $persona_id[0];
        return $this->render('alumno/index.html.twig', [
            'persona' => $persona,
            'alumnos' => $alumnoRepository->findBy(['persona' => $value]),
        ]);

    }
}

Local/templates/alumno/_delete_form.html.twig
<form method="post" action="{{ path('app_alumno_delete', {'id': alumno.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ alumno.id) }}">
    <button class="btn">Borrar</button>
</form>

Local/templates/alumno/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success mt-1">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

Local/templates/alumno/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Estudiante{% endblock %}

{% block body %}
    <h1>Editar Estudiante</h1>

    {{ include('alumno/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_alumno_index') }}">Volver</a>

    {{ include('alumno/_delete_form.html.twig') }}
{% endblock %}

Local/templates/alumno/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Estudiantes{% endblock %}

{% block body %}
    <h1>Estudiantes</h1>
            <form action="{{ path('search_alumnos') }}" method="get">
            <input type="number" name="dni" placeholder="Buscar por dni" class="form-control">            
            <button type="submit" class="btn btn-info mt-1">Buscar</button>
        </form>
    <table class="table">
        <thead>
            <tr>
                
                <th>Titulo_sec</th>
                <th>Escuela_sec</th>
                <th>Anio_egreso</th>
                <th>Dni/Pasaporte</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Telefono</th>
                <th>Partido</th>
                <th>Calle</th>
                <th>Numero</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for alumno in alumnos %}
            <tr>
                
                <td>{{ alumno.tituloSec }}</td>
                <td>{{ alumno.escuelaSec }}</td>
                <td>{{ alumno.anioEgreso }}</td>
                <td>{{ alumno.persona.dnipasaporte }}</td>
                <td>{{ alumno.persona.nombre }}</td> 
                <td>{{ alumno.persona.apellido }}</td>
                <td>{{ alumno.persona.telefono }}</td> 
                <td>{{ alumno.persona.partido}}</td>  
                <td>{{ alumno.persona.calle }}</td>    
                <td>{{ alumno.persona.numero }}</td>                                                             
                <td>
                    <a href="{{ path('app_alumno_show', {'id': alumno.id}) }}">Mostrar</a>
                    {% if is_granted ('ROLE_SUPER_ADMIN') or is_granted ('ROLE_ADMIN') %}
                        <a href="{{ path('app_alumno_edit', {'id': alumno.id}) }}">Editar</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">No se encontraron registros</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_alumno_new') }}">Nuevo Estudiante</a>
{% endblock %}

Local/templates/alumno/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Crear Nuevo Estudiante{% endblock %}

{% block body %}
<div class="container">
    <h1>Crear Nuevo Estudiante</h1>

    {{ include('alumno/_form.html.twig') }}
    
    <a href="{{ path('app_alumno_index') }}">Volver</a>
</div>
{% endblock %}

Local/templates/alumno/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Estudiante{% endblock %}

{% block body %}
    <h1>Estudiante</h1>

    <table class="table">
        <tbody>
         
            <tr>
                <th>Titulo_sec</th>
                <td>{{ alumno.tituloSec }}</td>
            </tr>
            <tr>
                <th>Escuela_sec</th>
                <td>{{ alumno.escuelaSec }}</td>
            </tr>
            <tr>
                <th>Anio_egreso</th>
                <td>{{ alumno.anioEgreso }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_alumno_index') }}">Volver</a>

    <a href="{{ path('app_alumno_edit', {'id': alumno.id}) }}">Editar</a>

    {{ include('alumno/_delete_form.html.twig') }}
{% endblock %}