Regional/src/Entity/Tecnicatura.php
<?php

namespace App\Entity;

use App\Repository\TecnicaturaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TecnicaturaRepository::class)]
class Tecnicatura
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nombre = null;

    #[ORM\Column]
    private ?int $duracion = null;

    #[ORM\Column(nullable: true)]
    private ?int $cantidad_asignaturas = null;

    #[ORM\Column(length: 30)]
    private ?string $numero_resolucion = null;

    #[ORM\ManyToOne(inversedBy: 'tecnicatura')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Modalidad $modalidad = null;

    #[ORM\OneToMany(mappedBy: 'tecnicatura', targetEntity: OfertaEducativa::class)]
    private Collection $ofertaeducativa;

    public function __construct()
    {
        $this->ofertaeducativa = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDuracion(): ?int
    {
        return $this->duracion;
    }

    public function setDuracion(int $duracion): static
    {
        $this->duracion = $duracion;

        return $this;
    }

    public function getCantidadAsignaturas(): ?int
    {
        return $this->cantidad_asignaturas;
    }

    public function setCantidadAsignaturas(?int $cantidad_asignaturas): static
    {
        $this->cantidad_asignaturas = $cantidad_asignaturas;

        return $this;
    }

    public function getNumeroResolucion(): ?string
    {
        return $this->numero_resolucion;
    }

    public function setNumeroResolucion(string $numero_resolucion): static
    {
        $this->numero_resolucion = $numero_resolucion;

        return $this;
    }

    public function getModalidad(): ?Modalidad
    {
        return $this->modalidad;
    }

    public function setModalidad(?Modalidad $modalidad): static
    {
        $this->modalidad = $modalidad;

        return $this;
    }

    /**
     * @return Collection<int, OfertaEducativa>
     */
    public function getOfertaeducativa(): Collection
    {
        return $this->ofertaeducativa;
    }

    public function addOfertaeducativa(OfertaEducativa $ofertaeducativa): static
    {
        if (!$this->ofertaeducativa->contains($ofertaeducativa)) {
            $this->ofertaeducativa->add($ofertaeducativa);
            $ofertaeducativa->setTecnicatura($this);
        }

        return $this;
    }

    public function removeOfertaeducativa(OfertaEducativa $ofertaeducativa): static
    {
        if ($this->ofertaeducativa->removeElement($ofertaeducativa)) {
            // set the owning side to null (unless already changed)
            if ($ofertaeducativa->getTecnicatura() === $this) {
                $ofertaeducativa->setTecnicatura(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getNombre();
    }

}

Regional/src/Form/TecnicaturaType.php
<?php

namespace App\Form;

use App\Entity\Tecnicatura;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TecnicaturaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
            ->add('duracion')
            ->add('cantidad_asignaturas')
            ->add('numero_resolucion')
            ->add('modalidad')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tecnicatura::class,
        ]);
    }
}

Regional/src/Controller/TecnicaturaController.php
<?php

namespace App\Controller;

use App\Entity\Tecnicatura;
use App\Form\TecnicaturaType;
use App\Repository\TecnicaturaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/tecnicatura')]
class TecnicaturaController extends AbstractController
{
    #[Route('/', name: 'app_tecnicatura_index', methods: ['GET'])]
    public function index(TecnicaturaRepository $tecnicaturaRepository): Response
    {
        return $this->render('tecnicatura/index.html.twig', [
            'tecnicaturas' => $tecnicaturaRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_tecnicatura_new', methods: ['GET', 'POST'])]
    public function new(Request $request, TecnicaturaRepository $tecnicaturaRepository): Response
    {
        $tecnicatura = new Tecnicatura();
        $form = $this->createForm(TecnicaturaType::class, $tecnicatura);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tecnicaturaRepository->save($tecnicatura, true);

            return $this->redirectToRoute('app_tecnicatura_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('tecnicatura/new.html.twig', [
            'tecnicatura' => $tecnicatura,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tecnicatura_show', methods: ['GET'])]
    public function show(Tecnicatura $tecnicatura): Response
    {
        return $this->render('tecnicatura/show.html.twig', [
            'tecnicatura' => $tecnicatura,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_tecnicatura_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Tecnicatura $tecnicatura, TecnicaturaRepository $tecnicaturaRepository): Response
    {
        $form = $this->createForm(TecnicaturaType::class, $tecnicatura);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tecnicaturaRepository->save($tecnicatura, true);

            return $this->redirectToRoute('app_tecnicatura_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('tecnicatura/edit.html.twig', [
            'tecnicatura' => $tecnicatura,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tecnicatura_delete', methods: ['POST'])]
    public function delete(Request $request, Tecnicatura $tecnicatura, TecnicaturaRepository $tecnicaturaRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tecnicatura->getId(), $request->request->get('_token'))) {
            $tecnicaturaRepository->remove($tecnicatura, true);
        }

        return $this->redirectToRoute('app_tecnicatura_index', [], Response::HTTP_SEE_OTHER);
    }
}

Regional/templates/tecnicatura/_delete_form.html.twig
<form method="post" action="{{ path('app_tecnicatura_delete', {'id': tecnicatura.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tecnicatura.id) }}">
    <button class="btn">Eliminar</button>
</form>

Regional/templates/tecnicatura/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Tecnicatura{% endblock %}

{% block body %}
    <h1>Editar Tecnicatura</h1>

    {{ include('tecnicatura/_form.html.twig', {'button_label': 'Actualizar'}) }}

    <a href="{{ path('app_tecnicatura_index') }}">Volver</a>

    {{ include('tecnicatura/_delete_form.html.twig') }}
{% endblock %}

Regional/templates/tecnicatura/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tecnicaturas{% endblock %}

{% block body %}
    <h1>Tecnicaturas</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Duracion</th>
                <th>Cantidad_asignaturas</th>
                <th>Numero_resolucion</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for tecnicatura in tecnicaturas %}
            <tr>
                <td>{{ tecnicatura.nombre }}</td>
                <td>{{ tecnicatura.duracion }}</td>
                <td>{{ tecnicatura.cantidadAsignaturas }}</td>
                <td>{{ tecnicatura.numeroResolucion }}</td>
                <td>
                    <a href="{{ path('app_tecnicatura_show', {'id': tecnicatura.id}) }}">Mostrar</a>
                    <a href="{{ path('app_tecnicatura_edit', {'id': tecnicatura.id}) }}">Edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no se encontraron datos</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_tecnicatura_new') }}">Crear</a>
{% endblock %}

Regional/templates/tecnicatura/muestra.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tecnicatura{% endblock %}

{% block body %}
    <h1>Tecnicaturas</h1>

    <table class="table" border=1>
        <tbody>
            <tr>
                <th>Nombre</th>
                <td>{{ tecnicatura.nombre }}</td>
            </tr>
            <tr>
                <th>Duracion</th>
                <td>{{ tecnicatura.duracion }}</td>
            </tr>
            <tr>
                <th>Cantidad_asignaturas</th>
                <td>{{ tecnicatura.cantidadAsignaturas }}</td>
            </tr>
            <tr>
                <th>Numero_resolucion</th>
                <td>{{ tecnicatura.numeroResolucion }}</td>
            </tr>
        </tbody>
    </table>

{% endblock %}

Regional/templates/tecnicatura/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nuena Tecnicatura{% endblock %}

{% block body %}
    <h1>Crear nueva Tecnicatura</h1>

    {{ include('tecnicatura/_form.html.twig') }}

    <a href="{{ path('app_tecnicatura_index') }}">Volver</a>
{% endblock %}

Regional/templates/tecnicatura/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tecnicatura{% endblock %}

{% block body %}
    <h1>Tecnicatura</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nombre</th>
                <td>{{ tecnicatura.nombre }}</td>
            </tr>
            <tr>
                <th>Duracion</th>
                <td>{{ tecnicatura.duracion }}</td>
            </tr>
            <tr>
                <th>Cantidad_asignaturas</th>
                <td>{{ tecnicatura.cantidadAsignaturas }}</td>
            </tr>
            <tr>
                <th>Numero_resolucion</th>
                <td>{{ tecnicatura.numeroResolucion }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_tecnicatura_index') }}">Volver</a>

    <a href="{{ path('app_tecnicatura_edit', {'id': tecnicatura.id}) }}">Editar</a>

    {{ include('tecnicatura/_delete_form.html.twig') }}
{% endblock %}